# Generated by Django 4.2.20 on 2025-03-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('local', 'Local'), ('host', 'Host')], max_length=10)),
                ('base_datos', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo', models.CharField(max_length=50)),
            ],
        ),
    ]
