# Generated by Django 4.2.20 on 2025-03-25 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eje_estrategico', models.CharField(max_length=255)),
                ('objetivo_estrategico', models.TextField()),
                ('indicador', models.TextField()),
                ('meta_2025', models.CharField(max_length=100)),
                ('avance', models.CharField(choices=[('0%', '0%'), ('20%', '20%'), ('En proceso', 'En proceso'), ('100%', '100%')], default='0%', max_length=100)),
                ('nivel', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], default='Bajo', max_length=50)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
