# Generated by Django 4.2.20 on 2025-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0002_tablero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReglaAcceso',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='tablero',
            name='accion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='avance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='nivel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tablero',
            name='responsable',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
