# Generated by Django 4.2.20 on 2025-04-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablero',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='tablero',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
