# Generated by Django 4.2.20 on 2025-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0005_alter_tablero_options_tablero_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='avance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
