# Generated by Django 4.2.20 on 2025-05-02 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planilla', '0006_alter_tablero_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planilla.tablero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
