# Generated by Django 4.2.20 on 2025-05-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0007_historialcambio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialcambio',
            old_name='fecha_cambio',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='historialcambio',
            old_name='tablero',
            new_name='indicador',
        ),
        migrations.RemoveField(
            model_name='historialcambio',
            name='campo_modificado',
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='campo',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='valor_anterior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historialcambio',
            name='valor_nuevo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
