# Generated by Django 4.2.20 on 2025-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0008_rename_fecha_cambio_historialcambio_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
