# Generated by Django 4.2.20 on 2025-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0009_tablero_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='tipo_meta',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('numero', 'Número'), ('texto', 'Texto')], default='porcentaje', max_length=20),
        ),
    ]
