# Generated by Django 4.2.20 on 2025-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0011_historialavance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
