# Generated by Django 4.2.20 on 2025-06-27 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planilla', '0012_tablero_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialavance',
            name='avance_anterior',
        ),
        migrations.RemoveField(
            model_name='historialavance',
            name='avance_nuevo',
        ),
        migrations.AddField(
            model_name='historialavance',
            name='avance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historialavance',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='historial_evidencias/'),
        ),
        migrations.AlterField(
            model_name='historialavance',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historialavance',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
