# Generated by Django 4.2.20 on 2025-09-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0014_bitacoraacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('editor', 'Editor'), ('lector', 'Lector'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
