# Generated by Django 5.2.6 on 2025-09-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0015_perfilusuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialavance',
            name='evidencia',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='evidencia',
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='planilla.historialavance')),
            ],
        ),
    ]
