# Generated by Django 5.2.6 on 2025-09-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0016_remove_historialavance_evidencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidencia',
            old_name='historial',
            new_name='historial_avance',
        ),
    ]
