# Generated by Django 5.2.6 on 2025-09-17 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0017_rename_historial_evidencia_historial_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='historial_evidencias/')),
                ('nombre_original', models.CharField(help_text='Nombre del archivo original subido por el usuario', max_length=255)),
                ('historial_avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_historicas', to='planilla.historialavance')),
            ],
        ),
    ]
